name: Build Bash CLI and run unit test

on:
  pull_request:
    branches: [
      main,
      bash_cli
    ]
  push:
    branches: [
      main,
      bash_cli
    ]


jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        working-directory: ./Bash_CLI
        run: pip install .
      - name: Test with pytest
        working-directory: ./Bash_CLI
        run: |
          pip install pytest
          pytest
